### ISSUE TITLE
Compile on Debian Jessie: missing 'openjdk-6-jdk'

### ISSUE THREAD

**Issue by dxmaxwell** [epicsdeb/visualdct#1]
While attempting to build this package on Debian Jessie I received the following error:

```
The following packages have unmet dependencies:
  pbuilder-satisfydepends-dummy : Depends: openjdk-6-jdk which is a virtual package.
Unable to resolve dependencies!  Giving up...
```

It seems that 'openjdk-6-jdk' package has been removed from Jessie.

Can the dependencies for this package be updated to 'openjdk-7-jdk'?

**Comment by berryma4** [comment]
maybe "default-jdk"

**Comment by mdavidsaver** [comment]
> maybe "default-jdk"

Yes, I think so these days.  default-jdk was gcj-jdk when I last updated this package.

**Comment by mdavidsaver** [comment]
Updated, 0df74c73a81852665420ac4141ad391d85867ea5 now builds for me on deb8 amd64 w/ openjdk 7.  Please confirm.

**Comment by dxmaxwell** [comment]
Builds correctly for me now. Thanks.
